// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#include "adder.h"
#include <stdlib.h>

// Exported Functions from `wasi:cli/run@0.2.3`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void exports_wasi_cli_run_result_void_void_free(exports_wasi_cli_run_result_void_void_t *ptr) {
  if (!ptr->is_err) {
  }
}

// Component Adapters

__attribute__((__export_name__("wasi:cli/run@0.2.3#run")))
int32_t __wasm_export_exports_wasi_cli_run_run(void) {
  exports_wasi_cli_run_result_void_void_t ret;
  ret.is_err = !exports_wasi_cli_run_run();
  int32_t result;
  if ((ret).is_err) {
    result = 1;
  } else {
    result = 0;
  }
  return result;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_adder(void);
void __component_type_object_force_link_adder_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_adder();
}
