// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#ifndef __BINDINGS_ADDER_H
#define __BINDINGS_ADDER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct {
  bool is_err;
} exports_wasi_cli_run_result_void_void_t;

// Exported Functions from `wasi:cli/run@0.2.3`
bool exports_wasi_cli_run_run(void);

// Helper Functions

void exports_wasi_cli_run_result_void_void_free(exports_wasi_cli_run_result_void_void_t *ptr);


#ifdef __cplusplus
}
#endif
#endif
