import os
import re
import shutil
from pathlib import Path
from urllib.request import urlopen

import pytest
from utils import clang_supports_wasm, cli_mode_available, run_cli, run_tool

UPSTREAM_ENABLED = os.environ.get("TARAWASM_UPSTREAM_IT") == "1"
UPSTREAM_MODE = os.environ.get("TARAWASM_UPSTREAM_MODE", "docker")

UPSTREAM_WIT_FIXTURES = [
    {
        "id": "componentize-py-foo-sdk",
        "lang": "python",
        "repo": "bytecodealliance/componentize-py",
        "rev": "89af297898960efc48575d4c166d03b399568269",
        "path": "src/test/foo_sdk/wit/world.wit",
    },
    {
        "id": "go-modules-issue163",
        "lang": "go",
        "repo": "bytecodealliance/go-modules",
        "rev": "f86e52384b611aa6962a954a52d2d2fac876e4d6",
        "path": "testdata/issues/issue163.wit",
    },
    {
        "id": "componentize-js-hello",
        "lang": "js",
        "repo": "bytecodealliance/componentize-js",
        "rev": "ab6483f82ee47df4b0eab74a2533e24075fdbb83",
        "path": "test/cases/hello/world.wit",
    },
    {
        "id": "cargo-component-example",
        "lang": "rust",
        "repo": "bytecodealliance/cargo-component",
        "rev": "1495f6141420528dfb745dd7da94a618e58d84b2",
        "path": "example/wit/example.wit",
    },
    {
        "id": "wit-bindgen-simple-functions",
        "lang": "c",
        "repo": "bytecodealliance/wit-bindgen",
        "rev": "a4170e042f184741f6d78e33061a3180b05c08de",
        "path": "tests/codegen/simple-functions.wit",
    },
]

WORLD_RE = re.compile(r"^\s*world\s+([A-Za-z][A-Za-z0-9_-]*)\s*[{]", re.MULTILINE)


def _raw_wit_url(repo: str, rev: str, path: str) -> str:
    return f"https://raw.githubusercontent.com/{repo}/{rev}/{path}"


def _download_text(url: str) -> str:
    with urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def _extract_world(wit_text: str) -> str:
    match = WORLD_RE.search(wit_text)
    if not match:
        raise ValueError("Unable to detect `world` declaration in upstream WIT")
    return match.group(1)


def _assert_bind_artifacts(lang: str, work_dir: Path) -> None:
    if lang in {"go", "js"}:
        assert (work_dir / "internal").exists()
    elif lang == "rust":
        assert (work_dir / "src" / "bindings.rs").exists()
    elif lang == "c":
        generated_headers = list(work_dir.glob("*.h"))
        generated_c_files = [p for p in work_dir.glob("*.c") if p.name != "component.c"]
        assert generated_headers, "No C headers generated by bind"
        assert generated_c_files, "No generated C binding source file found"
    elif lang == "python":
        assert any(p.name == "__init__.py" for p in work_dir.rglob("__init__.py"))
    else:
        raise AssertionError(f"Unsupported language in test fixture: {lang}")


@pytest.mark.skipif(
    not UPSTREAM_ENABLED,
    reason="Set TARAWASM_UPSTREAM_IT=1 to run upstream integration tests",
)
@pytest.mark.parametrize("fixture", UPSTREAM_WIT_FIXTURES, ids=lambda item: item["id"])
def test_bind_with_upstream_wit_fixtures(tmp_path, fixture):
    if not cli_mode_available(UPSTREAM_MODE):
        pytest.skip(f"CLI mode '{UPSTREAM_MODE}' is not available in this environment")

    if UPSTREAM_MODE != "docker" and shutil.which("wkg") is None:
        pytest.skip("wkg is not available on host for upstream fixture build")

    if (
        UPSTREAM_MODE != "docker"
        and fixture["lang"] == "c"
        and not clang_supports_wasm()
    ):
        pytest.skip("clang is not built with wasm32-unknown-wasi target")

    work_dir = tmp_path
    source_wit_dir = work_dir / "upstream-wit"
    source_wit_dir.mkdir()

    wit_text = _download_text(
        _raw_wit_url(fixture["repo"], fixture["rev"], fixture["path"])
    )
    world = _extract_world(wit_text)
    (source_wit_dir / "world.wit").write_text(wit_text)

    run_tool(
        work_dir,
        "wkg",
        "wit",
        "build",
        "--wit-dir",
        "upstream-wit",
        "--output",
        "fixture.wasm",
        mode=UPSTREAM_MODE,
    )

    run_cli(
        work_dir,
        "init",
        "--lang",
        fixture["lang"],
        "--wasm-file",
        "fixture.wasm",
        world,
        mode=UPSTREAM_MODE,
    )

    expected_wit = (
        work_dir / "wit" / "world.wit"
        if fixture["lang"] == "rust"
        else work_dir / "wit" / f"{world}.wit"
    )
    assert expected_wit.exists(), f"Expected extracted WIT file missing: {expected_wit}"

    run_cli(work_dir, "bind", mode=UPSTREAM_MODE)

    _assert_bind_artifacts(fixture["lang"], work_dir)
