// Code generated by wit-bindgen-go. DO NOT EDIT.

package run

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "wasi:cli/run@0.2.3".
var Exports struct {
	// Run represents the caller-defined, exported function "run".
	//
	//	run: func() -> result
	Run func() (result cm.BoolResult)
}
