[package]
name = "adder"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.42.1", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:adder"

[package.metadata.component.dependencies]
