name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo make install
          echo "/opt/wasi-sdk/bin" >> $GITHUB_PATH

      - name: Verify system toolchain
        run: make system-check

      - name: Verify SDK & Python deps
        run: make sdk-check

      - name: Install development dependencies
        run: pip install -r requirements-dev.txt

      - name: Install Wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Build CLI binary
        run: |
          make build
          echo "${{ github.workspace }}/target" >> $GITHUB_PATH

      - name: Run non-docker pytest tests (python and standalone modes)
        env:
          WASM_RUNTIME: wasmtime
        run: pytest -k "not cli:docker" -vv
